<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Objectives" data-toc-modified-id="Objectives-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Objectives</a></span></li><li><span><a href="#Ensemble-Methods" data-toc-modified-id="Ensemble-Methods-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Ensemble Methods</a></span><ul class="toc-item"><li><span><a href="#Advantages-&amp;--Disadvantages" data-toc-modified-id="Advantages-&amp;--Disadvantages-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Advantages &amp;  Disadvantages</a></span></li><li><span><a href="#Some-Types-of-Ensembles" data-toc-modified-id="Some-Types-of-Ensembles-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Some Types of Ensembles</a></span><ul class="toc-item"><li><span><a href="#Stacking" data-toc-modified-id="Stacking-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>Stacking</a></span></li><li><span><a href="#Bagging" data-toc-modified-id="Bagging-2.2.2"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span>Bagging</a></span></li><li><span><a href="#Boosting" data-toc-modified-id="Boosting-2.2.3"><span class="toc-item-num">2.2.3&nbsp;&nbsp;</span>Boosting</a></span></li></ul></li></ul></li><li><span><a href="#Aggregating:-Averaging,-Bagging,-and-Random-Forests" data-toc-modified-id="Aggregating:-Averaging,-Bagging,-and-Random-Forests-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Aggregating: Averaging, Bagging, and Random Forests</a></span><ul class="toc-item"><li><span><a href="#Data-Preparation-for-Examples" data-toc-modified-id="Data-Preparation-for-Examples-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Data Preparation for Examples</a></span></li><li><span><a href="#Averaging" data-toc-modified-id="Averaging-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Averaging</a></span><ul class="toc-item"><li><span><a href="#Model-1---Logistic-Regression" data-toc-modified-id="Model-1---Logistic-Regression-3.2.1"><span class="toc-item-num">3.2.1&nbsp;&nbsp;</span>Model 1 - Logistic Regression</a></span></li><li><span><a href="#Model-2---KNN" data-toc-modified-id="Model-2---KNN-3.2.2"><span class="toc-item-num">3.2.2&nbsp;&nbsp;</span>Model 2 - KNN</a></span></li><li><span><a href="#Model-3---Decision-Tree" data-toc-modified-id="Model-3---Decision-Tree-3.2.3"><span class="toc-item-num">3.2.3&nbsp;&nbsp;</span>Model 3 - Decision Tree</a></span></li><li><span><a href="#Averaging-the-Models" data-toc-modified-id="Averaging-the-Models-3.2.4"><span class="toc-item-num">3.2.4&nbsp;&nbsp;</span>Averaging the Models</a></span></li></ul></li><li><span><a href="#Bagging" data-toc-modified-id="Bagging-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Bagging</a></span><ul class="toc-item"><li><span><a href="#Bagging-Algorithm" data-toc-modified-id="Bagging-Algorithm-3.3.1"><span class="toc-item-num">3.3.1&nbsp;&nbsp;</span>Bagging Algorithm</a></span></li><li><span><a href="#Back-to-the-Example-Data" data-toc-modified-id="Back-to-the-Example-Data-3.3.2"><span class="toc-item-num">3.3.2&nbsp;&nbsp;</span>Back to the Example Data</a></span></li><li><span><a href="#Fitting-a-Random-Forest" data-toc-modified-id="Fitting-a-Random-Forest-3.3.3"><span class="toc-item-num">3.3.3&nbsp;&nbsp;</span>Fitting a Random Forest</a></span></li><li><span><a href="#An-Aside-Story---Bananas-🍌" data-toc-modified-id="An-Aside-Story---Bananas-🍌-3.3.4"><span class="toc-item-num">3.3.4&nbsp;&nbsp;</span>An Aside Story - Bananas 🍌</a></span></li><li><span><a href="#The-Goods-&amp;-The-Bads" data-toc-modified-id="The-Goods-&amp;-The-Bads-3.3.5"><span class="toc-item-num">3.3.5&nbsp;&nbsp;</span>The Goods &amp; The Bads</a></span></li><li><span><a href="#Breed-a-Variety-of-Trees" data-toc-modified-id="Breed-a-Variety-of-Trees-3.3.6"><span class="toc-item-num">3.3.6&nbsp;&nbsp;</span>Breed a Variety of Trees</a></span></li><li><span><a href="#Back-to-the-Example-Data" data-toc-modified-id="Back-to-the-Example-Data-3.3.7"><span class="toc-item-num">3.3.7&nbsp;&nbsp;</span>Back to the Example Data</a></span></li><li><span><a href="#Cool-Features-of-Random-Forests" data-toc-modified-id="Cool-Features-of-Random-Forests-3.3.8"><span class="toc-item-num">3.3.8&nbsp;&nbsp;</span>Cool Features of Random Forests</a></span></li><li><span><a href="#Extremely-Randomized-Trees-(Extra-Trees)" data-toc-modified-id="Extremely-Randomized-Trees-(Extra-Trees)-3.3.9"><span class="toc-item-num">3.3.9&nbsp;&nbsp;</span>Extremely Randomized Trees (Extra Trees)</a></span></li></ul></li></ul></li><li><span><a href="#Stacking" data-toc-modified-id="Stacking-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Stacking</a></span><ul class="toc-item"><li><span><a href="#Initial-Data-Prep" data-toc-modified-id="Initial-Data-Prep-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Initial Data Prep</a></span></li><li><span><a href="#Splitting" data-toc-modified-id="Splitting-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Splitting</a></span></li><li><span><a href="#Setting-Up-a-Pipeline" data-toc-modified-id="Setting-Up-a-Pipeline-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Setting Up a Pipeline</a></span></li><li><span><a href="#Setting-Up-a-Stack" data-toc-modified-id="Setting-Up-a-Stack-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Setting Up a Stack</a></span></li><li><span><a href="#Comparison-with-Base-Estimators" data-toc-modified-id="Comparison-with-Base-Estimators-4.5"><span class="toc-item-num">4.5&nbsp;&nbsp;</span>Comparison with Base Estimators</a></span></li></ul></li></ul></div>

In [2]:
import numpy as np
import pandas as pd
import xlrd
import os
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV,\
cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier,\
ExtraTreesClassifier, VotingClassifier
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import StackingRegressor

# Objectives

SWBAT:

- Use `sklearn` to build voting models
- Describe the algorithm of bagging
- Describe the differences among simple bagging, random forest, and extra trees algorithms
- Implement bagging models in `sklearn`

# Ensemble Methods

Because many heads are better than one!

<img width=50% src='images/captain_planet.jpg'/>

> "With our powers combined..."

These models tend to perform very well and generalize well!

## Advantages &  Disadvantages

- Decreases variance → Less overfitting!
- More complexity (you have to train each model or part of model)
- Tends to take up more space (have to keep each model)

## Some Types of Ensembles

We can break up the different types of ensembles into a few main types.

### Stacking

<img src='images/stacking.jpg' width=50%/>

#### Different Models, Same Data

- A form of averaging multiple models
- Typically uses the same training data for every model
- The innovation comes from the use of different kinds of models

#### Meta-Classifier/Meta-Regressor

- First, we ask several different models to make predictions about the target
- Rather than taking a simple average or vote to determine the outcome, feed these results into a final model that makes the prediction based on the other models’ predictions
- If it seems like we are approaching a neural network...you are correct!

### Bagging 

![](images/bag_of_marbles.jpg)

> Train weak learners, combine together into one via voting

- Many models naturally overfit
- Randomization → New models
- New models overfit in different ways
- Aggregation → Smooth over different ways of overfitting to reduce variance

> Low variance since it averages out quirks it might've learned

#### Aggregation

- **B**ootstrap **AGG**regating
- Algorithm to repeat many times:
    + Create a sample from your data
    + Train a model (e.g. a decision tree) on that sample
- Final model comes by averaging over those many models

#### Three Levels

1. Train each model on random sample
2. Choose a random set of features at each decision point
3. Choose a path at random!

### Boosting

<img src="images/try_fail_success.jpg" width=50%/>

> New model attempts to predict where the previous model made mistakes

- Prevent overfitting from start
- Train an underfit model
- Update the model by training a _new model_ on the residuals of the previous  model
- Repeat!

# Aggregating: Averaging, Bagging, and Random Forests

We can imagine training different models (maybe with different conditions) and then having them "vote" on what they think is best.

## Data Preparation for Examples

> Let's prepare some data to do some examples

In [2]:
df = pd.read_csv('data/salaries.csv')
df.head()

Age  Education         Occupation   Relationship     Sex Target
0   39  Bachelors       Adm-clerical  Not-in-family    Male  <=50K
1   50  Bachelors    Exec-managerial        Husband    Male  <=50K
2   38    HS-grad  Handlers-cleaners  Not-in-family    Male  <=50K
3   53       11th  Handlers-cleaners        Husband    Male  <=50K
4   28  Bachelors     Prof-specialty           Wife  Female  <=50K

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Age           32561 non-null  int64 
 1   Education     32561 non-null  object
 2   Occupation    32561 non-null  object
 3   Relationship  32561 non-null  object
 4   Sex           32561 non-null  object
 5   Target        32561 non-null  object
dtypes: int64(1), object(5)
memory usage: 1.5+ MB


In [4]:
df.isna().sum().sum()

0

In [5]:
# Convert Target to 0 or 1
df['Target'] = df['Target'] == '>50K'

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    df.drop(['Relationship','Sex','Target'],axis=1), df['Target'], random_state=42)

In [7]:
ohe = OneHotEncoder(drop='first', sparse=False)
ohe.fit(X_train.select_dtypes('object'))

OneHotEncoder(drop='first', sparse=False)

In [8]:
X_tr_ohe = pd.DataFrame(ohe.transform(X_train.select_dtypes('object')),
                                  columns=ohe.get_feature_names(),
                                    index=X_train.index)

In [9]:
X_tr_ohe.head()

x0_11th  x0_12th  x0_1st-4th  x0_5th-6th  x0_7th-8th  x0_9th  \
29         0.0      0.0         0.0         0.0         0.0     0.0   
12181      0.0      0.0         0.0         0.0         0.0     0.0   
18114      1.0      0.0         0.0         0.0         0.0     0.0   
4278       0.0      0.0         0.0         0.0         0.0     0.0   
12050      0.0      0.0         0.0         0.0         0.0     0.0   

       x0_Assoc-acdm  x0_Assoc-voc  x0_Bachelors  x0_Doctorate  ...  \
29               0.0           0.0           0.0           0.0  ...   
12181            0.0           0.0           0.0           0.0  ...   
18114            0.0           0.0           0.0           0.0  ...   
4278             0.0           0.0           1.0           0.0  ...   
12050            0.0           0.0           1.0           0.0  ...   

       x1_Farming-fishing  x1_Handlers-cleaners  x1_Machine-op-inspct  \
29                    0.0                   0.0                   0.0   
12181                 0.0                   0.0                   1.0   
18114                 0.0                   0.0                   0.0   
4278                  0.0                   0.0                   0.0   
12050                 0.0                   0.0                   0.0   

       x1_Other-service  x1_Priv-house-serv  x1_Prof-specialty  \
29                  0.0                 0.0                0.0   
12181               0.0                 0.0                0.0   
18114               1.0                 0.0                0.0   
4278                0.0                 0.0                0.0   
12050               0.0                 0.0                0.0   

       x1_Protective-serv  x1_Sales  x1_Tech-support  x1_Transport-moving  
29                    0.0       0.0              0.0                  0.0  
12181                 0.0       0.0              0.0                  0.0  
18114                 0.0       0.0              0.0                  0.0  
4278                  0.0       0.0              0.0                  0.0  
12050                 0.0       1.0              0.0                  0.0  

[5 rows x 29 columns]

In [10]:
X_te_ohe = pd.DataFrame(ohe.transform(X_test.select_dtypes('object')),
                                  columns=ohe.get_feature_names(),
                                    index=X_test.index)


In [11]:
X_te_ohe.head()

x0_11th  x0_12th  x0_1st-4th  x0_5th-6th  x0_7th-8th  x0_9th  \
14160      0.0      0.0         0.0         0.0         0.0     0.0   
27048      0.0      0.0         0.0         0.0         0.0     0.0   
28868      0.0      0.0         0.0         0.0         0.0     0.0   
5667       0.0      0.0         0.0         0.0         0.0     0.0   
7827       0.0      0.0         0.0         0.0         0.0     0.0   

       x0_Assoc-acdm  x0_Assoc-voc  x0_Bachelors  x0_Doctorate  ...  \
14160            0.0           0.0           0.0           0.0  ...   
27048            0.0           0.0           0.0           0.0  ...   
28868            0.0           0.0           1.0           0.0  ...   
5667             0.0           0.0           1.0           0.0  ...   
7827             0.0           0.0           0.0           0.0  ...   

       x1_Farming-fishing  x1_Handlers-cleaners  x1_Machine-op-inspct  \
14160                 0.0                   0.0                   0.0   
27048                 0.0                   0.0                   0.0   
28868                 0.0                   0.0                   0.0   
5667                  0.0                   0.0                   1.0   
7827                  0.0                   0.0                   0.0   

       x1_Other-service  x1_Priv-house-serv  x1_Prof-specialty  \
14160               0.0                 0.0                0.0   
27048               0.0                 0.0                0.0   
28868               0.0                 0.0                0.0   
5667                0.0                 0.0                0.0   
7827                0.0                 0.0                0.0   

       x1_Protective-serv  x1_Sales  x1_Tech-support  x1_Transport-moving  
14160                 0.0       0.0              0.0                  0.0  
27048                 0.0       0.0              0.0                  0.0  
28868                 0.0       0.0              0.0                  0.0  
5667                  0.0       0.0              0.0                  0.0  
7827                  0.0       0.0              0.0                  0.0  

[5 rows x 29 columns]

## Averaging

> Each model uses the same data to train and then we "vote" to make a prediction

### Model 1 - Logistic Regression

In [12]:
lr = LogisticRegression()

lr.fit(X_tr_ohe, y_train)

LogisticRegression()

In [13]:
scores = cross_val_score(estimator=lr, X=X_tr_ohe,
                        y=y_train, cv=5)
scores

array([0.78808354, 0.78460278, 0.78235053, 0.78542179, 0.79320229])

In [14]:
np.median(scores)

0.7854217854217854

In [15]:
lr.score(X_te_ohe, y_test)

0.7895835892396511

### Model 2 - KNN

In [16]:
knn = KNeighborsClassifier(3)

knn.fit(X_tr_ohe, y_train)

KNeighborsClassifier(n_neighbors=3)

In [17]:
scores = cross_val_score(estimator=knn, X=X_tr_ohe,
                y=y_train, cv=5)
np.median(scores)

0.7352579852579852

In [18]:
knn.score(X_te_ohe, y_test)

0.7190762805552143

### Model 3 - Decision Tree

In [19]:
rt = DecisionTreeClassifier(random_state=42)

rt.fit(X_tr_ohe, y_train)

DecisionTreeClassifier(random_state=42)

In [20]:
scores = cross_val_score(estimator=rt, X=X_tr_ohe,
               y=y_train, cv=5)
scores

array([0.77968878, 0.78521704, 0.78296478, 0.78583129, 0.79299754])

In [21]:
np.median(scores)

0.7852170352170352

In [22]:
rt.score(X_te_ohe, y_test)

0.789952094337305

### Averaging the Models

#### Building a `VotingClassifier`

> Of course there's a Scikit-Learn class for that

In [23]:
avg = VotingClassifier(estimators=[
    ('lr', lr),
    ('knn', knn),
    ('rt', rt)])
avg.fit(X_tr_ohe, y_train)

VotingClassifier(estimators=[('lr', LogisticRegression()),
                             ('knn', KNeighborsClassifier(n_neighbors=3)),
                             ('rt', DecisionTreeClassifier(random_state=42))])

In [24]:
scores = cross_val_score(estimator=avg, X=X_tr_ohe,
               y=y_train, cv=5)
scores

array([0.78235053, 0.78501229, 0.78214578, 0.78439803, 0.79279279])

In [25]:
np.median(scores)

0.7843980343980343

In [26]:
# This should be the same as above!

avg.score(X_te_ohe, y_test)

0.789952094337305

#### Weighted Averaging with the `VotingClassifier`

> Even if the vote is 50-50, you'd probably side with the "smart" ones more

This meta-estimator is not as good as one of our base estimators, so in this case the averaging did not work very well. Realizing that the decision tree is performing better than the logistic regression and the k-nearest-neighbors model, however, we might decide to build a meta-estimator by calculating a **weighted average** of the base estimators' predictions. And we can weight, or bias, this estimator in favor of the best-performing base estimator. Suppose we weight the tree 40%, the knn model 20%, and the logistic regression 40%:

In [27]:
w_avg = VotingClassifier(estimators=[
    ('lr', lr),
    ('knn', knn),
    ('rt', rt)],
    weights=[0.4, 0.2, 0.4])
w_avg.fit(X_tr_ohe, y_train)

VotingClassifier(estimators=[('lr', LogisticRegression()),
                             ('knn', KNeighborsClassifier(n_neighbors=3)),
                             ('rt', DecisionTreeClassifier(random_state=42))],
                 weights=[0.4, 0.2, 0.4])

In [28]:
scores = cross_val_score(estimator=w_avg, X=X_tr_ohe,
                        y=y_train, cv=5)
scores

array([0.78235053, 0.78501229, 0.78214578, 0.78439803, 0.79279279])

In [29]:
np.median(scores)

0.7843980343980343

In [30]:
# This should be the same as above!

w_avg.score(X_te_ohe, y_test)

0.789952094337305

## Bagging

A single decision tree will often overfit your training data. Let's see if we have evidence of that in the current case:

In [31]:
rt.score(X_tr_ohe, y_train)

0.7878787878787878

<details>
    <summary><b>🧠 Knowledge Check</b>: What is this score? And why is it nearly equal to 1?</summary>
    <br/>
    <quote>
    This nearly perfect score on the training data is already evidence of model overfitting. There are steps one can take to help with this, like limiting the "depth" of the nodes. And of course we can use cross-validation to get a more honest estimate of model quality
    </quote>
</details>




In [32]:
scores = cross_val_score(estimator=rt, X=X_tr_ohe,
                y=y_train, cv=5)
scores

array([0.77968878, 0.78521704, 0.78296478, 0.78583129, 0.79299754])

In [33]:
np.median(scores)

0.7852170352170352

In [34]:
rt.score(X_te_ohe, y_test)

0.789952094337305

But it's often better to do something else: Plant another tree!

Of course, if a second tree is going to be of any value, it has to be *different from* the first. Here's a good algorithm for achieving that:

### Bagging Algorithm

- Take a sample of your X_train and fit a decision tree to it.
- Replace the first batch of data and repeat.
- When you've got as many trees as you like, make use of all your individual trees' predictions to come up with some holistic prediction. 
    - (Most obviously, we could take the average of our predictions, but there are other methods we might try.)

* Because we're resampling our data with replacement, we're *bootstrapping*.
* Because we're making use of our many samples' predictions, we're *aggregating*.
* Because we're bootstrapping and aggregating all in the same algorithm, we're *bagging*.

### Back to the Example Data

In [35]:
# Instatiate a BaggingRegessor
# Note the base esimator is by default a decision tree
bag = BaggingClassifier(n_estimators=100,
                       verbose=1,
                       random_state=1)

In [36]:
# Fit it

bag.fit(X_tr_ohe, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.8s finished


BaggingClassifier(n_estimators=100, random_state=1, verbose=1)

In [37]:
# Cross-validation

scores = cross_val_score(estimator=bag, X=X_tr_ohe,
               y=y_train, cv=5)
scores

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.2s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.3s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.3s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_j

array([0.77968878, 0.78480753, 0.78255528, 0.78542179, 0.79279279])

In [38]:
np.median(scores)

0.7848075348075348

In [39]:
# Score on test

bag.score(X_te_ohe, y_test)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s finished


0.7895835892396511

### Fitting a Random Forest

### An Aside Story - Bananas 🍌

Banana trees can be susceptible to [Panama's disease](https://en.wikipedia.org/wiki/Panama_disease)

![Many individual yellow bananas](images/bananas.jpg)

They're all clones!

Similarly, all the Decision Trees will be the same if given the same data! (A clone!!!)

### The Goods & The Bads

**The Goods**

- Super friend! 
- High performance 
    + low variance
- Transparent
    + inherited from Decision Trees
    

**The Bads**

- We got so many trees to plant...
- Computationally expensive
- Memory
    + all trees stored in memory
    + think back to k-Nearest Neighbors

### Breed a Variety of Trees

Let's add an extra layer of randomization: Instead of using *all* the features of my model to optimize a branch at each node, I'll just choose a subset of my features.

That's the essence of a random forest model. Note that there are now **two** levels of random sampling happening: To build a new tree, I'll be taking only some of my data points; and at any branching point in a tree, I'll be using only some of my features to determine the split.

#### Steps:

1. Save a portion of data for validation (**out-of-bag**), the rest for training (**bag**)
2. The data for training (**bag**) is then split up by randomly selecting predictors
3. Grow/train your tree with the training data using just those features
4. Use our validation set (**out-of-bag**), take out the columns used in our tree from the previous step, and predict using the tree & this *out-of-bag* data
5. Compare on how well the tree did *out-of-bag error*
6. Repeat to make new trees and use the result to "vote" for the final decision

### Back to the Example Data

> Here's the [documentation](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier) on `RandomForestClassifier`

In [40]:
# Instantiate a RandomForestClassifier

rfr = RandomForestClassifier(max_features='sqrt',
                            max_samples=0.5,
                            random_state=1)

In [41]:
# Fit it

rfr.fit(X_tr_ohe, y_train)

RandomForestClassifier(max_features='sqrt', max_samples=0.5, random_state=1)

In [42]:
# Cross-validation

scores = cross_val_score(estimator=rfr, X=X_tr_ohe,
               y=y_train, cv=5)
scores

array([0.78009828, 0.78480753, 0.78276003, 0.78583129, 0.79279279])

In [43]:
np.median(scores)

0.7848075348075348

In [44]:
# Score on test

score = rfr.score(X_te_ohe, y_test)
score

0.7897064242722024

In [45]:
X_te_ohe.columns

Index(['x0_11th', 'x0_12th', 'x0_1st-4th', 'x0_5th-6th', 'x0_7th-8th',
       'x0_9th', 'x0_Assoc-acdm', 'x0_Assoc-voc', 'x0_Bachelors',
       'x0_Doctorate', 'x0_HS-grad', 'x0_Masters', 'x0_Preschool',
       'x0_Prof-school', 'x0_Some-college', 'x1_Adm-clerical',
       'x1_Armed-Forces', 'x1_Craft-repair', 'x1_Exec-managerial',
       'x1_Farming-fishing', 'x1_Handlers-cleaners', 'x1_Machine-op-inspct',
       'x1_Other-service', 'x1_Priv-house-serv', 'x1_Prof-specialty',
       'x1_Protective-serv', 'x1_Sales', 'x1_Tech-support',
       'x1_Transport-moving'],
      dtype='object')

### Cool Features of Random Forests

There are some extra investigations we can do with random forests since they're built of decision trees.

> **NOTE**
>
> Not all of these are _specific_ to random forests and can be applied to other (ensemble) models

#### Investigate Your Forest 🌲🌲👀🌲🌲

We can check out our trained estimators after training the ensemble. This isn't necessarily unique to random forests, but since the base model is always a decision tree we can really investigate how the model is working!

In [46]:
model_estimators = rfr.estimators_ 
print(len(model_estimators))
model_estimators

100


[DecisionTreeClassifier(max_features='sqrt', random_state=1791095845),
 DecisionTreeClassifier(max_features='sqrt', random_state=2135392491),
 DecisionTreeClassifier(max_features='sqrt', random_state=946286476),
 DecisionTreeClassifier(max_features='sqrt', random_state=1857819720),
 DecisionTreeClassifier(max_features='sqrt', random_state=491263),
 DecisionTreeClassifier(max_features='sqrt', random_state=550290313),
 DecisionTreeClassifier(max_features='sqrt', random_state=1298508491),
 DecisionTreeClassifier(max_features='sqrt', random_state=2143362693),
 DecisionTreeClassifier(max_features='sqrt', random_state=630311759),
 DecisionTreeClassifier(max_features='sqrt', random_state=1013994432),
 DecisionTreeClassifier(max_features='sqrt', random_state=396591248),
 DecisionTreeClassifier(max_features='sqrt', random_state=1703301249),
 DecisionTreeClassifier(max_features='sqrt', random_state=799981516),
 DecisionTreeClassifier(max_features='sqrt', random_state=1666063943),
 DecisionTreeCl

In [47]:
print(f'Overall model\'s score was {score:.3f}')
print('='*70)

for model in model_estimators[:5]:
    display(model)
    model_score = model.score(X_te_ohe, y_test)
    print(f'\tModel gave score of {model_score:.3f}')

Overall model's score was 0.790


DecisionTreeClassifier(max_features='sqrt', random_state=1791095845)

	Model gave score of 0.785


DecisionTreeClassifier(max_features='sqrt', random_state=2135392491)

	Model gave score of 0.788


DecisionTreeClassifier(max_features='sqrt', random_state=946286476)

	Model gave score of 0.789


DecisionTreeClassifier(max_features='sqrt', random_state=1857819720)

	Model gave score of 0.789


DecisionTreeClassifier(max_features='sqrt', random_state=491263)

	Model gave score of 0.791


#### Feature Importance

We can use [`.feature_importances_`](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier.feature_importances_) property of the trained model to get an idea of what features mattered the most

In [48]:
feat_import = {name: score 
                   for name, score 
                       in zip(X_te_ohe.columns, rfr.feature_importances_)
}
feat_import

{'x0_11th': 0.020436800370345974,
 'x0_12th': 0.005586813609673215,
 'x0_1st-4th': 0.002832401878369992,
 'x0_5th-6th': 0.00449956084561272,
 'x0_7th-8th': 0.007417939096003576,
 'x0_9th': 0.006469245954173599,
 'x0_Assoc-acdm': 0.012908861984233471,
 'x0_Assoc-voc': 0.012589759779065277,
 'x0_Bachelors': 0.11588467310150585,
 'x0_Doctorate': 0.0647324061918156,
 'x0_HS-grad': 0.04313866471655069,
 'x0_Masters': 0.10875755957118347,
 'x0_Preschool': 0.0003709575093120798,
 'x0_Prof-school': 0.0910207076185668,
 'x0_Some-college': 0.02452113272575209,
 'x1_Adm-clerical': 0.023930523235957547,
 'x1_Armed-Forces': 0.00023284860506856683,
 'x1_Craft-repair': 0.019556215050028882,
 'x1_Exec-managerial': 0.17144786192787734,
 'x1_Farming-fishing': 0.007872668050033718,
 'x1_Handlers-cleaners': 0.01878735032648214,
 'x1_Machine-op-inspct': 0.011078307301323623,
 'x1_Other-service': 0.07534746714856022,
 'x1_Priv-house-serv': 0.003238979421149528,
 'x1_Prof-specialty': 0.08681428396161553,
 'x

### Extremely Randomized Trees (Extra Trees)

Sometimes we might want even one more bit of randomization. Instead of always choosing the *optimal* branching path, we might just choose a branching path at random. If we're doing that, then we've got extremely randomized trees.

There are now **three** levels of randomization: sampling of data, sampling of features, and random selection of branching paths.

In [49]:
# Instantiate an ExtraTreesRegressor

etr = ExtraTreesClassifier(max_features='sqrt',
                         max_samples=0.5,
                         bootstrap=True,
                         random_state=1)

In [50]:
# Fit it

etr.fit(X_tr_ohe, y_train)

ExtraTreesClassifier(bootstrap=True, max_features='sqrt', max_samples=0.5,
                     random_state=1)

In [51]:
# Cross-validation

scores = cross_val_score(estimator=etr, X=X_tr_ohe,
               y=y_train, cv=5)
scores

array([0.78009828, 0.78480753, 0.78276003, 0.78583129, 0.79279279])

In [52]:
np.median(scores)

0.7848075348075348

In [53]:
# Score on test

etr.score(X_te_ohe, y_test)

0.7897064242722024

# Stacking

Remember weighted averaging? Stacking is about using DS models to estimate those weights for us. This means we'll have one layer of base estimators and another layer that is "**trained to optimally combine the model predictions to form a new set of predictions**". See [this short blog post](https://blogs.sas.com/content/subconsciousmusings/2017/05/18/stacked-ensemble-models-win-data-science-competitions/) for more.

## Initial Data Prep

In [54]:
wb = xlrd.open_workbook('data/Sales Report.xls',
                        logfile=open(os.devnull, 'w'))

sales = pd.read_excel(wb)
sales = sales.dropna()

In [55]:
sales.dtypes

Row ID                    int64
Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code             float64
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

In [56]:
sales['Category'].value_counts()

Office Supplies    6020
Furniture          2119
Technology         1844
Name: Category, dtype: int64

In [57]:
sales['Sub-Category'].value_counts()

Binders        1523
Paper          1368
Furnishings     957
Phones          888
Storage         845
Art             795
Accessories     773
Chairs          616
Appliances      465
Labels          364
Tables          319
Envelopes       253
Bookcases       227
Fasteners       217
Supplies        190
Machines        115
Copiers          68
Name: Sub-Category, dtype: int64

In [58]:
X_num = sales[['Discount', 'Profit']].columns
X_cat = sales[['Category', 'Sub-Category']].columns

In [59]:
X = sales[['Discount', 'Profit',
          'Category', 'Sub-Category']]
y = sales['Sales']

## Splitting

In [60]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

## Setting Up a Pipeline

In [61]:
numTrans = Pipeline(steps=[
    ('scaler', StandardScaler())
])
catTrans = Pipeline(steps=[
    ('ohe', OneHotEncoder(drop='first',
                          sparse=False))
])

In [62]:
pp = ColumnTransformer(transformers=[
    ('num', numTrans, X_num),
    ('cat', catTrans, X_cat)
])

In [63]:
pp.fit(X_train)

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('scaler', StandardScaler())]),
                                 Index(['Discount', 'Profit'], dtype='object')),
                                ('cat',
                                 Pipeline(steps=[('ohe',
                                                  OneHotEncoder(drop='first',
                                                                sparse=False))]),
                                 Index(['Category', 'Sub-Category'], dtype='object'))])

In [64]:
X_tr_pp = pp.transform(X_train)

## Setting Up a Stack

In [65]:
estimators = [
    ('lr', LinearRegression()),
    ('knn', KNeighborsRegressor()),
    ('rt', DecisionTreeRegressor())
]

sr = StackingRegressor(estimators)

In [66]:
sr.fit(X_tr_pp, y_train)

StackingRegressor(estimators=[('lr', LinearRegression()),
                              ('knn', KNeighborsRegressor()),
                              ('rt', DecisionTreeRegressor())])

In [67]:
X_test_pp = pp.transform(X_test)

In [68]:
sr.score(X_test_pp, y_test)

0.8162244663070259

## Comparison with Base Estimators

In [69]:
lr = LinearRegression().fit(X_tr_pp, y_train)
lr.score(X_test_pp, y_test)

0.42942244281549513

In [70]:
knn = KNeighborsRegressor().fit(X_tr_pp, y_train)
knn.score(X_test_pp, y_test)

0.7963215988357311

In [71]:
rt = DecisionTreeRegressor().fit(X_tr_pp, y_train)
rt.score(X_test_pp, y_test)

0.24652017581657681