# Topic 04-Part 1: Python Libraries & NumPy

- onl01-dtsc-ft-022221
- 02/26/21

![libgif](https://media0.giphy.com/media/7E8lI6TkLrvvAcPXso/giphy.gif?cid=790b76115d360a95792e4333770609b8&rid=giphy.gif)

## Learning Objectives

#### Our goals today are to be able to:

- Identify and import Python modules and packages (libraries)
- Identify differences between NumPy and base Python in usage and operation
- **Activity: Create a new module of your own**

- **Get a Brief Intro to Pandas (will cover extensively for topic 05)**
    - `topic_04_pt-2_brief_intro_to_pandas-SG.ipynb`


#### Big questions for this lesson

- What is a package, what do packages do, and why might we want to use them?
- When do we want to use NumPy?
- How can we reuse our own functions beyond one notebook?


## To-Do 

- [ ] Potiential group to code raw-python code channgelngs (leet, hackerrank)
- [ ] add option to poll


## Announcements

- **Working on starting Specialized Group 1:1s next week.**
    - Will post a poll or form with questions to help me make the best groups.
    
- **Today at 4pm EST is our first Feelings Fridays.**
    - A chance to discuss how we are holding up, highs and lows, wins and challenges, etc. 
    
    - Special Guest: one of my recently graduated full-time students Jeff Spagnola.
    
    
- **New Zooom feature to try: polls**
    - Try the topic progress poll

## Questions?

- What’s the difference between np.zeros(5)  vs. np.zeros([1,5])?

- Throughout Topic 4 I found myself corrupting ‘df’ when changing / adding columns, and I would have to reset.  What is good practice to prevent that?

- Can you talk a little bit about utf-8 vs. latin-1 and how to know what encoding to use when reading files with Pandas?
- Is it fair to say that Pandas series make up dataframes? Each column/row is a series and together they make up the whole picture.

- I'm not sure what I'm looking for in a scatter matrix to identify which variables might be worth focusing on. Would we be looking for instances of the dots grouped in a narrow sloping line? How does it even work for some of the categorical examples in the Ames Housing dataset?
- Is .loc/.iloc always needed to select rows?

- 
- 


___

# Importing Python packages 

In an earlier lesson, we wrote a function to calculate the mean of an list. That was **tedious**. To make our code efficient we could store that function in a *python module* and call it later when we need it. 

And thankfully, other people have _also_ wrote and optimized functions and wrapped them into **modules** and **packages** (also known as _libraries_ )

![numpy](https://raw.githubusercontent.com/donnemartin/data-science-ipython-notebooks/master/images/numpy.png)

[NumPy](https://www.numpy.org/) is the fundamental package for scientific computing with Python. 


To import a package type `import` followed by the name of the library as shown below.

## Terminology

![mod2](https://raw.githubusercontent.com/jirvingphd/dsc-lp-libraries-numpy/master/img/modules2.png)

![packages3](https://raw.githubusercontent.com/jirvingphd/dsc-lp-libraries-numpy/master/img/packages3.png)

## pip & the Python Package Index

![python-fact](https://raw.githubusercontent.com/jirvingphd/dsc-lp-libraries-numpy/master/img/python_def.png)

![pypi](https://raw.githubusercontent.com/jirvingphd/dsc-lp-libraries-numpy/master/img/pypi_packages.png)

![pippack](https://raw.githubusercontent.com/jirvingphd/dsc-lp-libraries-numpy/master/img/package_redo.png)

In [3]:
## One of My PyPi packages for flatiron school data science  (fsds)
!pip install -U fsds
from fsds.imports import *

fsds v0.2.30 loaded.  Read the docs: https://fs-ds.readthedocs.io/en/latest/ 


[i] Pandas .iplot() method activated.


# First library we will import is `Numpy`

![numpy](https://raw.githubusercontent.com/donnemartin/data-science-ipython-notebooks/master/images/numpy.png)

[NumPy](https://www.numpy.org/) is the fundamental package for scientific computing with Python. 

To import a package type `import` followed by the name of the package as shown below.

In [4]:
import numpy # Look, ma! we're importing!
numpy

<module 'numpy' from '/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/numpy/__init__.py'>

In [5]:
l = [1,2,3]
x=numpy.array([1,2,3])
print(x)
x

[1 2 3]


array([1, 2, 3])

In [6]:
l

[1, 2, 3]

#### New type of object

In [7]:
type(x)

numpy.ndarray

#### Alias libraries

Many packages have a canonical way to import them with an abbreviated alias.

In [8]:
np

<module 'numpy' from '/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/numpy/__init__.py'>

In [9]:
import numpy as np # np = alias
y=np.array([4,5,6])
y

array([4, 5, 6])

#### Other standard aliases 

In [10]:
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels as sm
import seaborn as sns

### Import specific modules from a larger package

In [11]:
# sometimes we will want to import a specific module from a package
import matplotlib.pyplot as plt
from matplotlib import pyplot as plt 

What happens if we mess with naming conventions? For example, import one of our previous libraries as `print`.


**PLEASE NOTE THAT WE WILL HAVE TO RESET THE KERNEL AFTER RUNNING THIS.**<br> Comment out your code after running it.


In [1]:
# import seaborn as print

In [12]:
#Did we get an error? What about when we run the following command?

print(x)

#Restart your kernel and clear cells

[1 2 3]


#### Helpful links: package documentation

Packages have associated documentation to explain how to use the different tools included in a package.

_Sample of libraries_
- [NumPy](https://docs.scipy.org/doc/numpy/)
- [SciPy](https://docs.scipy.org/doc/scipy/reference/)
- [Pandas](http://pandas.pydata.org/pandas-docs/stable/)
- [Matplotlib](https://matplotlib.org/contents.html)

## NumPy versus base Python

Now that we know packages exist, why do we want to use them? Let us examine a comparison between base Python and Numpy.

Python has lists and normal python can do basic math. NumPy, however, has the helpful objects called **arrays**.

Numpy has a few advantages over base Python which we will look at.

### Numpy makes math easy

Because of numpy we can now get the **mean** and other quick math of lists and arrays.

In [13]:
example = [4,3,25,40,62,20]
print(np.mean(example))

25.666666666666668


#### Different types of arrays

In [14]:
names_list=['Bob','John','Sally']
names_array=numpy.char.array(['Bob','John','Sally']) #use numpy.array for numbers and numpy.char.array for strings
print(names_list)
print(names_array)

['Bob', 'John', 'Sally']
['Bob' 'John' 'Sally']


In [17]:
display(names_list)
display(names_array)
names_array

['Bob', 'John', 'Sally']

chararray(['Bob', 'John', 'Sally'], dtype='<U5')

chararray(['Bob', 'John', 'Sally'], dtype='<U5')

#### Array math in action

In [18]:
# Make a list and an array of three numbers

#your code here
numbers_list = [5,22,33,90]
numbers_array = np.array([5,22,33,90])

In [19]:
# divide your array by 2

numbers_array/2

array([ 2.5, 11. , 16.5, 45. ])

In [20]:
# divide your list by 2

numbers_list/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

Numpy arrays support the `div()` operator while python lists do not. There are other things that make it useful to utilize numpy over base python for evaluating data.

In [21]:
# shape tells us the size of the array

numbers_array.shape

(4,)

### Slicing in NumPy

In [22]:
# We remember slicing from lists
numbers_list = list(range(10))
numbers_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
numbers_list[3:7]

[3, 4, 5, 6]

In [24]:
# Slicing in NumPy Arrays is very similar!
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a.shape)
a

(3, 4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
a.shape

(3, 4)

In [27]:
a[:,2]

array([ 3,  7, 11])

In [28]:
# first 2 rows, columns 1 & 2 (remember 0-index!)
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

### Datatypes in NumPy


In [29]:
a.dtype

dtype('int64')

In [30]:
names_list.dtype

AttributeError: 'list' object has no attribute 'dtype'

In [31]:
a.astype(np.float64)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

### More Array Math 
#### Adding matrices 

In [32]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)

[[ 6.  8.]
 [10. 12.]]


In [33]:
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]


#### Subtracting matrices 

In [34]:
# Elementwise difference; both produce the array
# [[-4.0| -4.0]
#  [-4.0 -4.0]]
print(x - y)

[[-4. -4.]
 [-4. -4.]]


In [35]:
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]


#### Multiplying matrices 

In [36]:
# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)

[[ 5. 12.]
 [21. 32.]]


In [37]:
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]


#### Dividing matrices 

In [38]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [39]:
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


#### Raising matrices to powers 

In [40]:
# Elementwise square root; both produce the same array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(x ** (1/2))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [41]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


### Numpy is faster

Below, you will find a piece of code we will use to compare the speed of operations on a list and operations on an array. In this speed test, we will use the package [time](https://docs.python.org/3/library/time.html).

In [42]:
import time
import numpy as np

size_of_vec = 1000

def pure_python_version():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [X[i] + Y[i] for i in range(len(X))]
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t1


t1 = pure_python_version()
t2 = numpy_version()
print("python: " + str(t1), "numpy: "+ str(t2))
print("Numpy is in this example " + str(t1/t2) + " times faster!")

python: 0.00026488304138183594 numpy: 3.4809112548828125e-05
Numpy is in this example 7.609589041095891 times faster!


___

# Making Your Own Module: You're not limited to PyPI

Make your own modules
![pipmod](https://raw.githubusercontent.com/jirvingphd/dsc-lp-libraries-numpy/master/img/import_modules.png)

# ⏰ ACTIVITY: Making our own module

### Solution: https://github.com/flatiron-school/python-libraries-making-your-own-module/tree/solution

- The remainder of this notebook is a Pair Programming Activity (time=15-30 min(?))

    - We will break into groups of 2-3 students. 
    - One student will share their screen while the group works together to solve the tasks. 

    - Clone the activity repository to your computer (or [visit GitHub and fork it](https://github.com/flatiron-school/python-libraries-making-your-own-module) first so you can save your work.)
- If you don't care about forking it, just clone it instead: 
`git clone https://github.com/flatiron-school/python-libraries-making-your-own-module`

![modlife](https://media1.giphy.com/media/dW0KhIROCaAdCO0V3S/giphy.gif?cid=790b76115d36096678416c65519d8082&rid=giphy.gif)

In [54]:
# this option will re-import your module each time you save an update to it
%load_ext autoreload
%autoreload 2

In [55]:
import temperizer as tp
help(tp)
tp

Help on module temperizer:

NAME
    temperizer - An example library for converting temperatures.

FUNCTIONS
    convert_c_to_f(temperature_c)
        YOUR DOCSTRING HERE.
    
    convert_f_to_c(temperature_f)
        Convert Fahrenheit to Celsius.

FILE
    /Users/jamesirving/Documents/GitHub/_COHORT_NOTES/022221FT/Online-DS-FT-022221-Cohort-Notes/Phase_1/topic_04_python_libraries/temperizer.py




<module 'temperizer' from '/Users/jamesirving/Documents/GitHub/_COHORT_NOTES/022221FT/Online-DS-FT-022221-Cohort-Notes/Phase_1/topic_04_python_libraries/temperizer.py'>

### Example: Convert F to C

1. This function is already implemented in `temperizer.py`.
2. Notice that we can call the imported function and see the result.

In [56]:
# 32F should equal 0C
tp.convert_f_to_c(32)

0.0

In [57]:
# -40F should equal -40C
tp.convert_f_to_c(-40)

-40.0

In [58]:
# 212F should equal 100C
tp.convert_f_to_c(212)

100.0

### Your turn: Convert C to F

> 1. Find the stub function in `temperizer.py`
2. The word `pass` means "this space intentionally left blank."
3. Add your code _in place of_ the `pass` keyword, _below_ the docstring.
4. Run these cells and make sure that your code works.

#### Small note:

Docstrings (those lines with `""" """` on either side) allow us to create self-documented code. 

Now later, if you forget what each function does, you can use the `?` or `help` functions the same way you would with other functions, and your documentation will show up!

In [ ]:
# 0C should equal 32F
tp.convert_c_to_f(0)

In [ ]:
# -40C should equal -40F
tp.convert_c_to_f(-40)

In [ ]:
# 100C should equal 212F
tp.convert_c_to_f(100)

## Next: Adding New Functions

You need to add support for Kelvin to the `temperizer` library.

1. Create new _stub functions_ in `temperizer.py`:

    * `convert_c_to_k`
    * `convert_f_to_k`
    * `convert_k_to_c`
    * `convert_k_to_f`

    Start each function with a docstring and the `pass` keyword, e.g.:

    ```python
    def convert_f_to_k(temperature_f):
        """Convert Fahrenheit to Kelvin."""
        pass
    ```

2. Then, go back to `temperizer.py` to replace `pass` with your code.


3. Use the cells below to test and validate these functions, similar to the ones above. 
    - Use the temperatures from line 2 of each cell to confirm your function works.
    
    
4. Run the notebook cells to make sure that your new functions work.

In [ ]:
# convert_c_to_k 
# 32 C -> 305.15 K


In [ ]:
# convert_f_to_k
# 60 F -> 288.71 K


In [ ]:
# convert_k_to_c
# 100 K -> -173.15 C


In [ ]:
# convert_k_to_f
# 100 K -> -279.67


### Extra credit:

make a function in your temperizer that will take a temp in F, and print out:

```
The temperature [number] F is:
    - x in C
    - y in k
```

In [ ]:
tp.convert_f_to_all(89)

## Congrats!!

You've now made your own module of temperature conversion functions!

#### _Our goals today were to be able to_: <br/>

- Identify and import Python modules and packages (libraries)
- Identify differences between NumPy and base Python in usage and operation
- Create a new module of our own

# Appendix

### Numpy array and matrix creation functions

Take 5 minutes and explore each of the following functions.  What does each one do?  What is the syntax of each?
- `np.zeros()`
- `np.ones()`
- `np.full()`
- `np.eye()`
- `np.random.random()`

In [47]:
ar1 = np.zeros(5)
print(ar1.shape)
ar1

(5,)


array([0., 0., 0., 0., 0.])

In [50]:
# What’s the difference between np.zeros(5) vs. np.zeros([1,5])?
ar2 = np.zeros([1,5])
print(ar2.shape)
ar2#.reshape(-1,1)

(1, 5)


array([[0., 0., 0., 0., 0.]])

In [51]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [52]:
np.full((3,3),3.3)


array([[3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3]])

In [53]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
np.random.random(6)

![pippack](https://raw.githubusercontent.com/jirvingphd/dsc-lp-libraries-numpy/master/img/package_redo.png)